### ISSUE TITLE
Issues with SetVerdictModPacket(WithMark)

### ISSUE THREAD

**Issue by Zauberstuhl** [florianl/go-nfqueue#12]
Hi,

I am trying to modify a DNS packet and need some help.
Currently I am receiving following payload via `nfqueue.Attribute`:

```
00000000  45 00 00 48 7a 24 40 00  40 11 27 51 0a 00 42 fe  |E..Hz$@.@.'Q..B.|
00000010  0a 00 42 32 00 35 92 c8  00 34 4e da 32 c9 81 80  |..B2.5...4N.2...|
00000020  00 01 00 01 00 00 00 00  06 67 69 74 68 75 62 03  |.........github.|
00000030  63 6f 6d 00 00 01 00 01  c0 0c 00 01 00 01 00 00  |com.............|
00000040  00 04 00 04 8c 52 79 03                           |.....Ry.|
```

And my goal is to change the IP address from `140.82.121.3` to `140.82.212.3`.
Then the payload looks like:

```
00000000  45 00 00 48 7a 24 40 00  40 11 27 51 0a 00 42 fe  |E..Hz$@.@.'Q..B.|
00000010  0a 00 42 32 00 35 92 c8  00 34 4e da 32 c9 81 80  |..B2.5...4N.2...|
00000020  00 01 00 01 00 00 00 00  06 67 69 74 68 75 62 03  |.........github.|
00000030  63 6f 6d 00 00 01 00 01  c0 0c 00 01 00 01 00 00  |com.............|
00000040  00 04 00 04 8c 52 d4 03                           |.....R..|
```

If I now run the packet via `SetVerdictModPacketWithMark(id, 1, nfqueue.NfAccept, packet)`.
The modified packet wont be submitted. I also tried to simply send the original payload:

`SetVerdictModPacketWithMark(id, 1, nfqueue.NfAccept, *attr.Payload)`

Which doesn't work either. Have I misunderstood the function or is something fishy here =?

Kind regards,
zauberstuhl

**Comment by florianl** [comment]
Hi @Zauberstuhl 
Can you provide a minimal working example that demonstrates your problem?
Thanks, Florian

**Comment by florianl** [comment]
As there is no further follow up on this question, I close this issue.
Please don't hestiate to reopen it or create a new one if needed.
