### ISSUE TITLE
Under load the go-routine started by Register exit

### ISSUE THREAD

**Issue by mlitvin** [florianl/go-nfqueue#13]
Under load it is likely that any reading operation will get the enobuf error, and the default error handling stop reading at this point.

To make things worse there is no way for the application to know that something wrong has happened apart from the fact that it stop getting callbacks.

Right now robust application MUST write their own error handling to avoid those problems. This is probably the right solution and it should just be documented.

But in addition to documenting the behaviour it is probably better to ignore by default enobuf errors.

**Comment by florianl** [comment]
Thanks for your feedback.
Ignoring errors is not a pattern I'd like to support. Therefore I see your comment as request for improvement on documentation.

**Comment by florianl** [comment]
Updated the documentation with https://github.com/florianl/go-nfqueue/commit/c7799421e4e4228aa74aa634443db0ddc8375a4d.
