### ISSUE TITLE
How can i get ip from incoming packet?

### ISSUE THREAD

**Issue by fwflunky** [florianl/go-nfqueue#16]
Hello, How can i get ip and port from incoming packet?

**Comment by florianl** [comment]
hi :wave: 

There are two steps needed:
1. A firewall rule that redirects the incoming packets you want to inspect to a nfqueue queue
2. You need to attach your code that might be based on this package to this queue

If you want to see an example, take a look at the integration test of this package.
First Travis applies some iptables rules:
https://github.com/florianl/go-nfqueue/blob/9202b09686166b232129ee259873cc506ae743dc/.travis.yml#L19-L20
Then a config is prepared to attach to this queue:
https://github.com/florianl/go-nfqueue/blob/9202b09686166b232129ee259873cc506ae743dc/nfqueue_linux_integration_test.go#L13-L14
In this example the payload of every package is printed with the function that will be attached to the queue:
https://github.com/florianl/go-nfqueue/blob/9202b09686166b232129ee259873cc506ae743dc/nfqueue_linux_integration_test.go#L30-L36
And finally the function is attached to the queue:
https://github.com/florianl/go-nfqueue/blob/9202b09686166b232129ee259873cc506ae743dc/nfqueue_linux_integration_test.go#L39
