### ISSUE TITLE
TCP payload

### ISSUE THREAD

**Issue by losintikfos** [florianl/go-nfqueue#4]
I am trying to process TCP payload to perform HTTP header data checks before deciding on verdict. 

I have notice the HTTP payload is not received as part of the packet copied to the callback function. 

Please do you know how can achieve this? is there a specific flag or strategy I can use to achieve this?

Please suggest.

Thanks

**Comment by florianl** [comment]
Hi,
to which values do you set `Copymode` and `MaxPacketLen` in the `Config` struct?

Florian

**Comment by losintikfos** [comment]
I have been able to resolve this with iptable prerouting chain.

Thanks
