### ISSUE TITLE
Question: modifying packet content

### ISSUE THREAD

**Issue by Caesurus** [florianl/go-nfqueue#7]
Is it possible to modify the packet content with go-nfqueue, I couldn't see an example of how to achieve this. Some of the other modules out there do permit modifying the packet data, but they rely on the C library. I'd much prefer to stay 100% go only.

**Comment by florianl** [comment]
Hi @Caesurus 
it's not supported yet. It's still not on the todo list.
Sorry!

**Comment by Caesurus** [comment]
Thanks for the feedback, Closing the issue :)

**Comment by florianl** [comment]
Hi @Caesurus 
I've just updated the code, so this is now possible with `SetVerdictModPacket` and `SetVerdictModPacketWithMark`.

**Comment by Caesurus** [comment]
That's awesome @florianl thanks!
